package com.example.carelyo.service

import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.util.Log
import androidx.core.app.NotificationCompat
import com.example.carelyo.ui.auth.LoginActivity // Or your Dashboard Activity
import com.google.firebase.messaging.FirebaseMessagingService
import com.google.firebase.messaging.RemoteMessage

class CarelyoFirebaseMessagingService : FirebaseMessagingService() {

    override fun onNewToken(token: String) {
        super.onNewToken(token)
        Log.d("CarelyoFCM", "New token generated by system: $token")
        // Note: Tokens rotate occasionally. Your syncDeviceToken routine on application login catches this refresh cycle beautifully.
    }

    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        super.onMessageReceived(remoteMessage)
        Log.d("CarelyoFCM", "Payload packet received from sender source: ${remoteMessage.from}")

        // Check if message contains a notification payload
        remoteMessage.notification?.let {
            showNotification(it.title ?: "Reminder", it.body ?: "You have an upcoming event.")
        }

        // Check if message contains data payloads (custom key-value pairs from backend)
        if (remoteMessage.data.isNotEmpty()) {
            val title = remoteMessage.data["title"] ?: "Carelyo Alert"
            val message = remoteMessage.data["message"] ?: "Check your schedule details."
            showNotification(title, message)
        }
    }

    private fun showNotification(title: String, messageBody: String) {
        val intent = Intent(this, LoginActivity::class.java).apply {
            flags = Intent.FLAG_ACTIVITY_CLEAR_TOP
        }
        val pendingIntent = PendingIntent.getActivity(
            this, 0, intent,
            PendingIntent.FLAG_ONE_SHOT or PendingIntent.FLAG_IMMUTABLE
        )

        val channelId = "carelyo_reminders"
        val notificationBuilder = NotificationCompat.Builder(this, channelId)
            .setSmallIcon(android.R.drawable.ic_lock_idle_alarm) // Swap out with your custom app drawable asset icon later
            .setContentTitle(title)
            .setContentText(messageBody)
            .setAutoCancel(true)
            .setPriority(NotificationCompat.PRIORITY_HIGH)
            .setContentIntent(pendingIntent)

        val notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        notificationManager.notify(System.currentTimeMillis().toInt(), notificationBuilder.build())
    }
}